export enum FiltersEnum{
    sampleNumber = "broj uzorka",
    dateOfReading = "datum očitavanja",
    timeOfReading = "vrijeme očitavanja",
    dateOfValidation = "datum validiranja",
    analizatorName = "naziv analizatora",
    AssayName = "naziv pretrage",
    specimenID ="ID pacijenta",
    specimentID ="ID pacijenta",
    oib ="Oib pacijenta",
    controlSampleLot = "Lot kontrolnog uzorka",
    controlSampleTestName="Ime kontrolnog testa",
    controlSampleDate ="Datum kontrolnog testa",
    name = "Ime pacijenta",
    surname = "Prezime pacijenta",
    ddkNumber = "Broj DDK",
    code = "Dodijeljena šifra",
    testResult ="Rezultat testa",
    centerThatGetsTheBlood ="Centar koji prikuplja krv",
    positiveResults = "Pozitivni rezultati (da ili ne)",
    priority = "Prioritet",
    priorityReason = "Razlog",
    analizatorMark = "Oznaka analizatora",
    lot = "Lot",
    expirationDateReagens = "Datum isteka reagensa",
    dateRange = "Razdoblje od/do",
    validated = "Da li je validiran (VALIDATED ili NOT_VALIDATED)",
    analizatorDevice = "Odaberite analizator uređaj"


}